### ISSUE TITLE
can we run on normal mode?

### ISSUE THREAD

**Issue by timiil** [joshkunz/qemu-docker#11]
means without any privilege or cap_net parameters，could we?

**Comment by joshkunz** [comment]
It cannot be run unprivileged mode in a performant way. KVM requires privileged access, so without that QEMU has to resort to emulating the binary (which is very slow). If I remember correctly, QEMU also has a built-in networking stack that can be used to avoid mounting dev/tun or using the NET_ADMIN capability, but that will also slow things down (and likely be buggier than Linux's).

**Comment by psy0rz** [comment]
you might want to check out https://github.com/tianon/docker-qemu
